apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx # Selects pods with the label app: nginx
  ports:
    - protocol: TCP
      port: 80 # The port the service exposes
      targetPort: 80 # The port the container listens on
  type: LoadBalancer # Or ClusterIP, NodePort, depending on your needs
